name: My workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python script
        run: python streamlit_app.py
      - name: MY_API_KEY
        env: 
           MY_API_KEY: ${{ secrets.MY_API_KEY }}
        run: python streamlit_app.py
        
          
